vim.keymap.set("n", "<leader>me", "<cmd>RustLsp expandMacro<cr>", { desc = "expand macro" })

vim.api.nvim_create_user_command("Dbg", function()
    vim.cmd.RustLsp('debug')
end, { desc = "debug (search target from cursor)" })
vim.api.nvim_create_user_command("Dbgs", function()
    vim.cmd.RustLsp('debuggables')
end, { desc = "show debuggables" })
vim.api.nvim_create_user_command("Run", function()
    vim.cmd.RustLsp('run')
end, { desc = "run (search target from cursor)" })
vim.api.nvim_create_user_command("Runs", function()
    vim.cmd.RustLsp('runnables')
end, { desc = "show runnables" })
